### ISSUE TITLE
[Request] Linux/Steam Deck version please

### ISSUE THREAD

**Issue by CHJ85** [TimBurris/SiriusXMPlayer#4]
Hi there. Would it be possible for you to also develop this app for Linux? Or would that be too much work?
For the reasons you stated yourself, this is absolutely needed.
Thanks.

**Comment by TimBurris** [comment]
Until Microsoft has a true cross platform GUI that supports Linux out of the box, I do not plan to try providing a Linux version.  It's simply out of my wheelhouse :(

**Comment by CHJ85** [comment]
I understand. Thanks anyway.
